name: masraf_app
description: A modern expense tracking application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.0
  go_router: ^10.1.2
  intl: ^0.19.0
  fl_chart: ^0.63.0
  uuid: ^3.0.7
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  path_provider: ^2.1.1
  google_fonts: ^5.1.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.8.0
  google_sign_in: ^6.0.0
  image_picker: ^0.8.7+4
  firebase_storage: ^11.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
dependency_overrides:
  firebase_auth_web: 5.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21