// Generated by FlutterFire CLI

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBboBJgcVO8KjkCm-XD4jv06vBUPE_fj-8',
    authDomain: 'hackathon-632ae.firebaseapp.com',
    projectId: 'hackathon-632ae',
    storageBucket: 'hackathon-632ae.firebasestorage.app',
    messagingSenderId: '984774205172',
    appId: '1:984774205172:web:7f7e4a27d114c21deb08a1',
    measurementId: 'G-YB49GQE1WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBboBJgcVO8KjkCm-XD4jv06vBUPE_fj-8',
    appId: '1:984774205172:android:943fbd33ad49259eeb08a1',
    messagingSenderId: '984774205172',
    projectId: 'hackathon-632ae',
    storageBucket: 'hackathon-632ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBboBJgcVO8KjkCm-XD4jv06vBUPE_fj-8',
    appId: '1:984774205172:ios:XXXXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '984774205172',
    projectId: 'hackathon-632ae',
    storageBucket: 'hackathon-632ae.firebasestorage.app',
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBboBJgcVO8KjkCm-XD4jv06vBUPE_fj-8',
    appId: '1:984774205172:linux:XXXXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '984774205172',
    projectId: 'hackathon-632ae',
    storageBucket: 'hackathon-632ae.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBboBJgcVO8KjkCm-XD4jv06vBUPE_fj-8',
    appId: '1:984774205172:windows:XXXXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '984774205172',
    projectId: 'hackathon-632ae',
    storageBucket: 'hackathon-632ae.firebasestorage.app',
  );
}
